const fs = require('fs');
const path = require('path');

/**
 * Generates a .pgs file for LuciadRIA.
 * @param {string} outputDir 
 * @param {string} tableName 
 * @param {object} dbConfig 
 * @param {object} mapping 
 */
function generatePgs(outputDir, tableName, dbConfig, mapping) {
    const pgsPath = path.join(outputDir, `${tableName}.pgs`);
    
    let content = `# LuciadFusion Connection Descriptor for ${tableName}\n`;
    content += `driver   = org.postgresql.Driver\n`;
    content += `url      = jdbc:postgresql://${dbConfig.host}:${dbConfig.port}/${dbConfig.database}\n`;
    content += `user     = ${dbConfig.user}\n`;
    content += `password = ${dbConfig.password}\n\n`;
    
    content += `table         = ${tableName}\n`;
    content += `spatialColumn = geom\n`;
    content += `SRID          = 4326\n\n`;
    
    content += `# Feature columns to decode\n`;
    content += `featureNames.0 = id\n`;
    content += `featureNames.1 = resolution\n`;
    
    let index = 2;
    for (const [key, config] of Object.entries(mapping)) {
        content += `featureNames.${index} = ${config.column}\n`;
        index++;
    }
    
    content += `\n# Display names for the UI\n`;
    content += `featureDisplayNames.0 = H3 Index\n`;
    content += `featureDisplayNames.1 = Resolution\n`;
    
    index = 2;
    for (const [key, config] of Object.entries(mapping)) {
        content += `featureDisplayNames.${index} = ${config.displayName || config.column}\n`;
        index++;
    }
    
    content += `\n# Use the H3 Index as the primary key\n`;
    content += `primaryFeatureIndex = 0\n`;
    content += `primaryFeatureAutoGenerated = false\n\n`;
    
    content += `# Data types for reference\n`;
    content += `featureDataTypes.0 = TEXT\n`;
    content += `featureDataTypes.1 = INTEGER\n`;
    
    index = 2;
    for (const [key, config] of Object.entries(mapping)) {
        content += `featureDataTypes.${index} = ${config.type}\n`;
        index++;
    }
    
    content += `\n# Performance tuning for high cell counts\n`;
    content += `maxCacheSize = 1000\n`;

    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }
    
    fs.writeFileSync(pgsPath, content);
}

module.exports = { generatePgs };
